spring:
  application:
    name: airbnbBackend

  # DB Configurations
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1

jwt:
  secretKey: ${JWT_SECRET_KEY}

stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}
  webhook:
    key: ${STRIPE_WEBHOOK_SECRET}

frontendUrl: ${FRONTEND_URL:http://localhost:3000/}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
